name: CI/CD Pipeline 
# 워크플로 이름
# 워크플로가 실행되는 트리거 이벤트 여기서는 main 브랜치가 push가 일어났을 때
on:
  push:
    branches:
      - main
# 워크플로 내에서 실행할 작업 단위
# 워크플로를 구성하는 하나 이상의 작업을 정의
# 각 작업은 별도의 실행 환경(가상 머신)에서 실행됨.
# 각 작업은 이름, 실행 환경, 단계가 포함된다.
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2  # S3 버킷이 위치한 리전

    - name: Deploy to S3
      run: |
        aws s3 sync ./dist s3://jihyeon-builds-test --delete
        echo "S3 deployment completed!"

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID \
          --paths "/*"
        echo "CloudFront cache invalidation completed!"